### 1. GET /hello?name=Spring
GET localhost:8080/hello?name=Spring
Accept: application/json

### 2. POST /hello?name=Spring
POST localhost:8080/hello?name=Spring
Accept: application/json

### 1. GET /hello
GET localhost:8080/hello
Accept: application/json